/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BACKUP;

import atividade2.*;
import DAO.MateriasDAO;
import DTO.MateriasDTO;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.ImageIcon;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edval
 */
public class ControleMaterias extends javax.swing.JFrame {

    /**
     * Creates new form CADASTRO_USER_CORRETO
     */
    public ControleMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JToggleButton();
        quit = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMaterias = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtprofessor = new javax.swing.JTextField();
        btnCarregar = new javax.swing.JToggleButton();
        btnLimpar = new javax.swing.JToggleButton();
        btnAlterar = new javax.swing.JToggleButton();
        txttema = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtconteudo = new javax.swing.JTextField();
        txtmateria = new javax.swing.JTextField();
        txtdata = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        LABELimgvoltar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CONTROLE DE MATERIAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PROFESSOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID_MATERIAS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("________________________________________");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("________________________________________");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 200, -1));

        btnCadastrar.setBackground(new java.awt.Color(29, 27, 77));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 160, 50));

        quit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        quit.setForeground(new java.awt.Color(255, 255, 255));
        quit.setText("X");
        quit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitMouseClicked(evt);
            }
        });
        getContentPane().add(quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 20, -1));

        tabelaMaterias.setBackground(new java.awt.Color(29, 27, 77));
        tabelaMaterias.setForeground(new java.awt.Color(255, 255, 255));
        tabelaMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id_materias", "Professor", "Materia", "Tema", "Data", "Conteudo"
            }
        ));
        jScrollPane1.setViewportView(tabelaMaterias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 500, 440));

        btnPesquisar.setBackground(new java.awt.Color(29, 27, 77));
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("LISTAR DADOS");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 160, 50));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MATERIA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("________________________________________");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 200, -1));

        txtprofessor.setBackground(new java.awt.Color(29, 27, 77));
        txtprofessor.setForeground(new java.awt.Color(255, 255, 255));
        txtprofessor.setBorder(null);
        txtprofessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprofessorActionPerformed(evt);
            }
        });
        getContentPane().add(txtprofessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 20));

        btnCarregar.setBackground(new java.awt.Color(29, 27, 77));
        btnCarregar.setForeground(new java.awt.Color(255, 255, 255));
        btnCarregar.setText("CARREGAR CAMPOS");
        btnCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCarregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 50));

        btnLimpar.setBackground(new java.awt.Color(29, 27, 77));
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("LIMPAR CAMPOS");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 160, 50));

        btnAlterar.setBackground(new java.awt.Color(29, 27, 77));
        btnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterar.setText("Alterar Dados");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 160, 50));

        txttema.setBackground(new java.awt.Color(29, 27, 77));
        txttema.setForeground(new java.awt.Color(255, 255, 255));
        txttema.setBorder(null);
        txttema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttemaActionPerformed(evt);
            }
        });
        getContentPane().add(txttema, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 190, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("________________________________________");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, -1));

        jLabel11.setText("________________________________________");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 200, -1));

        txtconteudo.setBackground(new java.awt.Color(29, 27, 77));
        txtconteudo.setForeground(new java.awt.Color(255, 255, 255));
        txtconteudo.setBorder(null);
        txtconteudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconteudoActionPerformed(evt);
            }
        });
        getContentPane().add(txtconteudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 190, 20));

        txtmateria.setBackground(new java.awt.Color(29, 27, 77));
        txtmateria.setForeground(new java.awt.Color(255, 255, 255));
        txtmateria.setBorder(null);
        txtmateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmateriaActionPerformed(evt);
            }
        });
        getContentPane().add(txtmateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 190, 20));

        txtdata.setBackground(new java.awt.Color(29, 27, 77));
        txtdata.setForeground(new java.awt.Color(255, 255, 255));
        txtdata.setBorder(null);
        txtdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdataActionPerformed(evt);
            }
        });
        getContentPane().add(txtdata, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 190, 20));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("________________________________________");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TEMA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 40, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DATA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 40, -1));

        txtid.setBackground(new java.awt.Color(29, 27, 77));
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setBorder(null);
        txtid.setEnabled(false);
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, 20));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CONTEÚDO");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 90, -1));

        LABELimgvoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back_button40WHITE.png"))); // NOI18N
        LABELimgvoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LABELimgvoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LABELimgvoltarMouseClicked(evt);
            }
        });
        getContentPane().add(LABELimgvoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 50));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("________________________________________");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 200, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AF_LINGUIFY_LOGOMARCAPADRAO_RED.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 540, 570));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AF_LINGUIFY_LOGOMARCAPADRAO_RED.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, -40, 470, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public class BackgroundMenuBar extends JMenuBar {
    Color bgColor=Color.RED;

    public void setColor(Color color) {
        bgColor=color;
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setColor(bgColor);
        g2d.fillRect(0, 0, getWidth() - 1, getHeight() - 1);

    }
}
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        CadastrarMateria();
        listarValoresUsuario();
        LimparCampos();
//
//        String username, senha;
//
//        username = txtusername.getText();
//        senha = txtsenha.getText();
//        
//
//
//        UsuarioDTO objusuariodto = new UsuarioDTO();
//        objusuariodto.setUsername(username);
//        objusuariodto.setSenha(senha);
//
//        UsuarioDAO objusuariodao = new UsuarioDAO();
//        objusuariodao.cadastrarUsuario(objusuariodto);
//
//        try {
//
//        } catch (Exception e) {
//
//        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMouseClicked
        System.exit(0);     // TODO add your handling code here:
    }//GEN-LAST:event_quitMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       listarValoresUsuario(); // TODO add your handling code here:
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtprofessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprofessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprofessorActionPerformed

    private void btnCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregarActionPerformed
      CarregarCampos();  // TODO add your handling code here:
    }//GEN-LAST:event_btnCarregarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
    LimparCampos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarMateria();
        listarValoresUsuario();  
        LimparCampos();// TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txttemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttemaActionPerformed

    private void txtconteudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconteudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconteudoActionPerformed

    private void txtmateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmateriaActionPerformed

    private void txtdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdataActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void LABELimgvoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LABELimgvoltarMouseClicked
         MenuADM objmenuADMview = new MenuADM();
                objmenuADMview.setVisible(true);
                
                dispose();
    }//GEN-LAST:event_LABELimgvoltarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleMaterias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleMaterias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABELimgvoltar;
    private javax.swing.JToggleButton btnAlterar;
    private javax.swing.JToggleButton btnCadastrar;
    private javax.swing.JToggleButton btnCarregar;
    private javax.swing.JToggleButton btnLimpar;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel quit;
    private javax.swing.JTable tabelaMaterias;
    private javax.swing.JTextField txtconteudo;
    private javax.swing.JTextField txtdata;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmateria;
    private javax.swing.JTextField txtprofessor;
    private javax.swing.JTextField txttema;
    // End of variables declaration//GEN-END:variables

    
  // TODOS OS MÉTODOS UTILIZADOS  
    
    private void listarValoresUsuario() {

        try {
            MateriasDAO objmateriasdao = new MateriasDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaMaterias.getModel();
            model.setNumRows(0);

            ArrayList<MateriasDTO> lista = objmateriasdao.PesquisarMateria();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_materias(),
                    lista.get(num).getProfessor(),
                    lista.get(num).getMateria(),
                    lista.get(num).getTema(),
                    lista.get(num).getData(),
                    lista.get(num).getConteudo(),

                });
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar valores VIEW: " + erro);
        }

    }
    
    
    
    private void CarregarCampos(){
        int setar = tabelaMaterias.getSelectedRow();
        txtid.setText(tabelaMaterias.getModel().getValueAt(setar, 0).toString());
        txtprofessor.setText(tabelaMaterias.getModel().getValueAt(setar, 1).toString());
        txtmateria.setText(tabelaMaterias.getModel().getValueAt(setar, 2).toString());
        txttema.setText(tabelaMaterias.getModel().getValueAt(setar, 3).toString());
        txtdata.setText(tabelaMaterias.getModel().getValueAt(setar, 4).toString());
        txtconteudo.setText(tabelaMaterias.getModel().getValueAt(setar, 5).toString());
        txtid.setText(tabelaMaterias.getModel().getValueAt(setar, 6).toString());
    
    }
    
    
     private void CadastrarMateria(){
        String professor, materia, tema, data, conteudo;
        
        professor = txtprofessor.getText();
        materia = txtmateria.getText();        
        tema = txttema.getText();
        data= txtdata.getText();
        conteudo = txtconteudo.getText();
        
        


        MateriasDTO objmateriasdto = new MateriasDTO();
        objmateriasdto.setProfessor(professor);
        objmateriasdto.setMateria(materia);
        objmateriasdto.setTema(tema);
        objmateriasdto.setData(data);
        objmateriasdto.setProfessor(professor);

        MateriasDAO objmateriasdao = new MateriasDAO();
        objmateriasdao.cadastrarMateria(objmateriasdto);

       

}

    private void LimparCampos(){
    txtprofessor.setText("");
    txtconteudo.setText("");
    txtdata.setText("");
    txtmateria.setText("");
    txttema.setText("");
    
    txtprofessor.requestFocus();
    
    }
    
    
   private void AlterarMateria(){
       int id_materias;
       String professor, materia, tema, data, conteudo;
       
       id_materias = Integer.parseInt(txtid.getText());
       professor = txtprofessor.getText();
        materia = txtmateria.getText();        
        tema = txttema.getText();
        data= txtdata.getText();
        conteudo = txtconteudo.getText();
       
        MateriasDTO objmateriasdto = new MateriasDTO();
        objmateriasdto.setId_materias(id_materias);
        objmateriasdto.setProfessor(professor);
        objmateriasdto.setMateria(materia);
        objmateriasdto.setTema(tema);
        objmateriasdto.setData(data);
        objmateriasdto.setProfessor(professor);
       
       MateriasDAO objmateriasdao = new MateriasDAO();
       objmateriasdao.AlterarMateria(objmateriasdto);
       
   
   
   } 
    
    
    
    
    
}

